// Ternak Padel — seed data (Indonesian padel community flavor)

export const TP_DATA = {
  me: {
    name: "Tomy Santoso",
    user: "@tomy",
    initials: "TS",
    skill: "Intermediate",
    side: "Left",
    city: "Jakarta",
    memberSince: "2024",
  },
  players: [
    { id: "rina", name: "Rina Wijaya", initials: "RW", pts: 486 },
    { id: "eko", name: "Eko Prasetyo", initials: "EP", pts: 471 },
    { id: "maya", name: "Maya Lestari", initials: "ML", pts: 455 },
    { id: "dimas", name: "Dimas Putra", initials: "DP", pts: 431 },
    { id: "fitri", name: "Fitri Handayani", initials: "FH", pts: 419 },
    { id: "bayu", name: "Bayu Nugroho", initials: "BN", pts: 412 },
    { id: "sari", name: "Sari Kusuma", initials: "SK", pts: 398 },
    { id: "me", name: "Tomy Santoso", initials: "TS", pts: 380, me: true },
    { id: "andre", name: "Andre Halim", initials: "AH", pts: 371 },
    { id: "dina", name: "Dina Maharani", initials: "DM", pts: 360 },
    { id: "raka", name: "Raka Aditya", initials: "RA", pts: 344 },
  ],
  events: [
    {
      id: "fri-americano",
      title: "Friday Night Americano",
      type: "Americano",
      day: "FRI",
      date: "13",
      dateLong: "Jum'at, 13 Juni · 19:00–22:00",
      venue: "Padel Pro SCBD",
      courts: 4,
      fee: 100000,
      pts: 10,
      max: 16,
      joined: 10,
      today: true,
      live: false,
      desc: "Weekly social Americano. All levels welcome — smart pairing keeps every game close.",
      roster: ["rina", "bayu", "sari", "andre", "dina", "eko", "maya", "dimas", "fitri", "raka"],
    },
    {
      id: "sat-mexicano",
      title: "Mexicano Social",
      type: "Mexicano",
      day: "SAB",
      date: "14",
      dateLong: "Sabtu, 14 Juni · 16:00–19:00",
      venue: "Jakarta Padel Club, Senayan",
      courts: 3,
      fee: 85000,
      pts: 10,
      max: 12,
      joined: 8,
      desc: "Dynamic Mexicano — pairings reshuffle by live standings every round.",
      roster: ["dina", "raka", "fitri", "eko", "sari", "maya", "bayu", "andre"],
    },
    {
      id: "sun-league",
      title: "Summer League · Week 7",
      type: "League",
      day: "MIN",
      date: "15",
      dateLong: "Minggu, 15 Juni · 09:00–13:00",
      venue: "Padel Arena Kemang",
      courts: 4,
      fee: 150000,
      pts: 25,
      max: 16,
      joined: 16,
      full: true,
      desc: "Season 3 league round. Tournament weighting — +25 ranking points at stake.",
      roster: ["rina", "eko", "maya", "dimas", "fitri", "bayu", "sari", "andre"],
    },
    {
      id: "wed-koth",
      title: "KOTH Night",
      type: "King of the Hill",
      day: "RAB",
      date: "18",
      dateLong: "Rabu, 18 Juni · 20:00–22:00",
      venue: "Padel Pro SCBD",
      courts: 2,
      fee: 75000,
      pts: 10,
      max: 8,
      joined: 5,
      desc: "Climb the courts. Win and move up, lose and move down. Court 1 is the throne.",
      roster: ["bayu", "andre", "raka", "dina", "eko"],
    },
  ],
  feed: [
    { id: "f1", who: "Dina Maharani", ini: "DM", time: "2h", kind: "result", text: "defeated Raka / Fitri", score: "6–3", sub: "Mexicano Social · +12 pts", likes: 12, comments: 3 },
    { id: "f2", who: "Bayu Nugroho", ini: "BN", time: "5h", kind: "rank", text: "moved up to Rank #6", score: "↑2", sub: "Season 3 ladder", likes: 18, comments: 5 },
    { id: "f3", who: "Sari Kusuma", ini: "SK", time: "1d", kind: "badge", text: "earned the Undefeated badge", score: "🏅", sub: "10 wins in a row", likes: 31, comments: 8 },
    { id: "f4", who: "Eko Prasetyo", ini: "EP", time: "1d", kind: "join", text: "joined Summer League · Week 7", score: "", sub: "Padel Arena Kemang", likes: 6, comments: 1 },
    { id: "f5", who: "Maya Lestari", ini: "ML", time: "2d", kind: "result", text: "defeated Dimas / Andre", score: "7–5", sub: "KOTH Night · +10 pts", likes: 14, comments: 2 },
  ],
  timeline: [
    { id: "t1", kind: "W", title: "Won 6–2 vs Andre / Sari", sub: "Friday Americano · 6 Jun", pts: "+12" },
    { id: "t2", kind: "badge", title: "Earned 'Social Butterfly'", sub: "Played with 50 unique players · 4 Jun", pts: "" },
    { id: "t3", kind: "W", title: "Won 6–4 vs Raka / Dina", sub: "Mexicano Social · 31 Mei", pts: "+10" },
    { id: "t4", kind: "L", title: "Lost 4–6 vs Bayu / Rina", sub: "KOTH Night · 28 Mei", pts: "+2" },
    { id: "t5", kind: "rank", title: "Moved up to Rank #8", sub: "Season 3 · 25 Mei", pts: "↑1" },
    { id: "t6", kind: "W", title: "Won 6–3 vs Eko / Maya", sub: "Friday Americano · 23 Mei", pts: "+12" },
  ],
  badges: [
    { id: "b1", icon: "🎾", name: "First Match", got: true },
    { id: "b2", icon: "⚔️", name: "Iron Player", sub: "50 matches", got: true },
    { id: "b3", icon: "🦋", name: "Social Butterfly", sub: "50 partners", got: true },
    { id: "b4", icon: "🔥", name: "Undefeated", sub: "10 straight", got: false },
    { id: "b5", icon: "👑", name: "KOTH Winner", got: false },
    { id: "b6", icon: "🏆", name: "Champion", got: false },
  ],
  rankHistory: [19, 17, 16, 14, 15, 12, 11, 11, 10, 9, 8, 8],
  seasons: [
    { id: "s3", name: "Season 3", rank: "#8", now: true },
    { id: "s2", name: "Season 2", rank: "#11" },
    { id: "s1", name: "Season 1", rank: "#19" },
  ],
};

export const rupiah = (n) => "Rp " + n.toLocaleString("id-ID");
